/*
this will minify the html after the html has been generated by 
using the template  
*/


function PostProcessHtmlMinify(options) {
  // Configure your plugin with options... 

   this.options = options || {};
}
 
PostProcessHtmlMinify.prototype.apply = function(compiler) {
  // ... 
  compiler.plugin('compilation', function(compilation) {

   // console.log('The compiler is starting a new compilation...');
 
    compilation.plugin('html-webpack-plugin-after-html-processing', function(htmlPluginData, callback) {

        var minifyOptions = {
           collapseWhitespace: true,
           removeComments: true,
           removeRedundantAttributes: true,
           removeScriptTypeAttributes: true,
           removeStyleLinkTypeAttributes: true,
           processScripts: ['text/ng-template'] //minify angular templates also
        };

        var minify = require('html-minifier').minify;
        htmlPluginData.html = minify(htmlPluginData.html, minifyOptions);

      callback(null, htmlPluginData);

    });

  });
 
};
 
module.exports = PostProcessHtmlMinify;